
export type TNarrationStyle = "Traditional" | "First-Person" | "Dialogue-Driven" | "Third-Person Limited" | "Persuasive" | "Expository" | "Nonlinear" | "Multiple Perspectives"


export const NarrationStyle: { [name in TNarrationStyle]: string } = {
    "Traditional": "This is a storytelling style that typically follows a chronological order, presenting events as they happen in time from beginning to end. Traditional narratives often have a clear introduction, development of conflict, climax, and resolution. The emphasis is on a coherent, linear storyline that the reader can follow easily",
    "First-Person": "In a first-person narrative, the story is told from the perspective of a character within the story, usually denoted by the pronoun 'I.' This style provides direct insight into the narrator’s thoughts, feelings, and experiences. The reader sees the world and events filtered through that character’s subjective viewpoint, which can create intimacy and immediacy, as well as limitations if the narrator is unreliable or biased",
    "Dialogue-Driven": "A dialogue-driven narrative is one in which the plot, character development, and thematic elements are revealed primarily through the characters’ spoken interactions rather than through extensive description or exposition. In this approach, conversations between characters carry the story forward, offering insights into their personalities, relationships, and conflicts.",
    "Third-Person Limited": "In a third-person limited narrative, the story is told by an external narrator who refers to the characters using pronouns like 'he,' 'she,' or 'they.' However, the narrator’s knowledge and perspective are limited to the inner thoughts and feelings of only one character (or a few select characters) rather than having an all-knowing vantage point. This style allows readers to connect closely with a particular character’s experiences while maintaining some narrative distance.",
    "Persuasive": "A persuasive narrative aims to convince the reader of a particular point of view or argument. It weaves storytelling elements with rhetoric, logic, and emotional appeals to influence the reader’s beliefs or actions. Rather than merely presenting a sequence of events, a persuasive narrative focuses on shaping the reader’s opinion or persuading them to adopt a specific perspective.",
    "Expository": "An expository narrative focuses on explaining, informing, or clarifying a topic. While it may include storytelling elements or examples, its main goal is to provide the reader with clear, factual, and organized information. It often uses a logical structure and direct language to ensure the reader gains understanding or knowledge about the subject at hand.",
    "Nonlinear": "A nonlinear narrative does not follow a straight, chronological path. Instead, it might jump forward or backward in time, use flashbacks or flash-forwards, or present events out of sequence. This can create suspense, highlight thematic contrasts, or show how different events are interconnected. By breaking the traditional timeline, nonlinear narratives can offer richer complexity in how a story is perceived and understood.",
    "Multiple Perspectives": "A multiple perspectives narrative presents the story from the viewpoints of several different characters or narrators. Each perspective might offer unique insights, biases, and interpretations of events. This style enables readers to see how the same situation can be understood in diverse ways, fostering deeper complexity, empathy, and critical thinking as the audience must piece together a multifaceted understanding of the narrative."
}