
export type TNarrationStyle = "Traditional" | "First-Person" | "Dialogue-Driven" | "Third-Person Limited" | "Persuasive" | "Expository" | "Nonlinear" | "Multiple Perspectives"


export const NarrationStyleEn: { [name in TNarrationStyle]: string } = {
    "Traditional": "This is a storytelling style that typically follows a chronological order, presenting events as they happen in time from beginning to end. Traditional narratives often have a clear introduction, development of conflict, climax, and resolution. The emphasis is on a coherent, linear storyline that the reader can follow easily",
    "First-Person": "In a first-person narrative, the story is told from the perspective of a character within the story, usually denoted by the pronoun 'I.' This style provides direct insight into the narrator’s thoughts, feelings, and experiences. The reader sees the world and events filtered through that character’s subjective viewpoint, which can create intimacy and immediacy, as well as limitations if the narrator is unreliable or biased",
    "Dialogue-Driven": "A dialogue-driven narrative is one in which the plot, character development, and thematic elements are revealed primarily through the characters’ spoken interactions rather than through extensive description or exposition. In this approach, conversations between characters carry the story forward, offering insights into their personalities, relationships, and conflicts.",
    "Third-Person Limited": "In a third-person limited narrative, the story is told by an external narrator who refers to the characters using pronouns like 'he,' 'she,' or 'they.' However, the narrator’s knowledge and perspective are limited to the inner thoughts and feelings of only one character (or a few select characters) rather than having an all-knowing vantage point. This style allows readers to connect closely with a particular character’s experiences while maintaining some narrative distance.",
    "Persuasive": "A persuasive narrative aims to convince the reader of a particular point of view or argument. It weaves storytelling elements with rhetoric, logic, and emotional appeals to influence the reader’s beliefs or actions. Rather than merely presenting a sequence of events, a persuasive narrative focuses on shaping the reader’s opinion or persuading them to adopt a specific perspective.",
    "Expository": "An expository narrative focuses on explaining, informing, or clarifying a topic. While it may include storytelling elements or examples, its main goal is to provide the reader with clear, factual, and organized information. It often uses a logical structure and direct language to ensure the reader gains understanding or knowledge about the subject at hand.",
    "Nonlinear": "A nonlinear narrative does not follow a straight, chronological path. Instead, it might jump forward or backward in time, use flashbacks or flash-forwards, or present events out of sequence. This can create suspense, highlight thematic contrasts, or show how different events are interconnected. By breaking the traditional timeline, nonlinear narratives can offer richer complexity in how a story is perceived and understood.",
    "Multiple Perspectives": "A multiple perspectives narrative presents the story from the viewpoints of several different characters or narrators. Each perspective might offer unique insights, biases, and interpretations of events. This style enables readers to see how the same situation can be understood in diverse ways, fostering deeper complexity, empathy, and critical thinking as the audience must piece together a multifaceted understanding of the narrative."
}

export const NarrationStyleEs: { [name in TNarrationStyle]: string } = {
    "Traditional": "Este es un estilo de narración que normalmente sigue un orden cronológico, presentando los eventos tal como ocurren en el tiempo desde el principio hasta el final. Las narrativas tradicionales suelen tener una introducción clara, desarrollo del conflicto, clímax y resolución. El énfasis está en una historia coherente y lineal que el lector pueda seguir fácilmente.",
    "First-Person": "En una narrativa en primera persona, la historia es contada desde la perspectiva de un personaje dentro de la historia, generalmente denotado por el pronombre 'yo'. Este estilo ofrece una visión directa de los pensamientos, sentimientos y experiencias del narrador. El lector ve el mundo y los eventos filtrados a través del punto de vista subjetivo de ese personaje, lo que puede crear intimidad e inmediatez, así como limitaciones si el narrador es poco fiable o está sesgado.",
    "Dialogue-Driven": "Una narrativa impulsada por el diálogo es aquella en la que la trama, el desarrollo de los personajes y los elementos temáticos se revelan principalmente a través de las interacciones habladas de los personajes, en lugar de una descripción extensa o exposición. En este enfoque, las conversaciones entre los personajes llevan la historia hacia adelante, ofreciendo ideas sobre sus personalidades, relaciones y conflictos.",
    "Third-Person Limited": "En una narrativa en tercera persona limitada, la historia es contada por un narrador externo que se refiere a los personajes utilizando pronombres como 'él', 'ella' o 'ellos'. Sin embargo, el conocimiento y la perspectiva del narrador están limitados a los pensamientos y sentimientos internos de solo un personaje (o de unos pocos personajes seleccionados) en lugar de tener un punto de vista omnisciente. Este estilo permite a los lectores conectar estrechamente con las experiencias de un personaje en particular, mientras se mantiene cierta distancia narrativa.",
    "Persuasive": "Una narrativa persuasiva tiene como objetivo convencer al lector de un punto de vista o argumento particular. Combina elementos narrativos con retórica, lógica y apelaciones emocionales para influir en las creencias o acciones del lector. En lugar de simplemente presentar una secuencia de eventos, una narrativa persuasiva se enfoca en moldear la opinión del lector o persuadirlo para adoptar una perspectiva específica.",
    "Expository": "Una narrativa expositiva se centra en explicar, informar o aclarar un tema. Aunque puede incluir elementos narrativos o ejemplos, su objetivo principal es proporcionar al lector información clara, factual y organizada. A menudo utiliza una estructura lógica y un lenguaje directo para garantizar que el lector adquiera comprensión o conocimiento sobre el tema en cuestión.",
    "Nonlinear": "Una narrativa no lineal no sigue un camino cronológico recto. En su lugar, puede saltar hacia adelante o hacia atrás en el tiempo, usar retrospecciones o anticipaciones, o presentar eventos fuera de secuencia. Esto puede crear suspense, resaltar contrastes temáticos o mostrar cómo diferentes eventos están interconectados. Al romper la línea de tiempo tradicional, las narrativas no lineales pueden ofrecer una mayor complejidad en cómo se percibe y comprende una historia.",
    "Multiple Perspectives": "Una narrativa de múltiples perspectivas presenta la historia desde los puntos de vista de varios personajes o narradores diferentes. Cada perspectiva puede ofrecer ideas, sesgos e interpretaciones únicas de los eventos. Este estilo permite a los lectores ver cómo una misma situación puede ser entendida de formas diversas, fomentando una mayor complejidad, empatía y pensamiento crítico, ya que la audiencia debe armar una comprensión multifacética de la narrativa."
};
