import { GptType } from "./gpt"

export type VoiceType = "Basic" | "Advanced"

type SubscriptionType = {
    [name: string]: {
        id: string,
        name: string,
        price: number | null,
        discountPercentage: number,
        maxWordCount: number,
        maxSecondsPerStory: number,
        freeUsageSecondsAmount: number,
        dialogues: boolean,
        coverImage: boolean,
        userHistory: boolean,
        customCharacterLimit: number,
        customEnvironmentLimit: number,
        customStoryInput: boolean,
        voicType: VoiceType,
        continuationOfStory: boolean,
        gptModel: GptType,
        extraStoryPrice: number,
        packageColor: string,
        revenueCat: {
            identifier: string,
            identifierMonthly: string,
            identifierOTP: string,
        }
    }
}

export const Subscription: SubscriptionType = {
    "Free": {
        id: "Free",
        name: "Free",
        revenueCat: {
            identifier: "Free",
            identifierMonthly: "Free",
            identifierOTP: "Free"
        },
        price: null,
        freeUsageSecondsAmount: 9 * 60,
        maxWordCount: 500,
        maxSecondsPerStory: 3 * 60,
        dialogues: false,
        coverImage: false,
        customStoryInput: false,
        userHistory: false,
        customCharacterLimit: 1,
        customEnvironmentLimit: 1,
        voicType: "Basic",
        continuationOfStory: false,
        gptModel: "gpt-3.5-turbo-16k",
        extraStoryPrice: 0.29,
        packageColor: "#c4c4c4",
        discountPercentage: 0,
    },
    "The Little Prince": {
        id: "The Little Prince",
        name: "The Little Prince",
        revenueCat: {
            identifier: "The Little Prince",
            identifierMonthly: "the_little_prince:monthly",
            identifierOTP: "OTP"
        },
        price: 2.99,
        freeUsageSecondsAmount: 30 * 60,
        maxWordCount: 1000,
        maxSecondsPerStory: 6 * 60,
        continuationOfStory: false,
        coverImage: false,
        customStoryInput: false,
        customCharacterLimit: 3,
        customEnvironmentLimit: 3,
        dialogues: false,
        gptModel: "gpt-3.5-turbo-16k",
        userHistory: true,
        voicType: "Basic",
        extraStoryPrice: 0.39,
        packageColor: "#854C1D",
        discountPercentage: 0,
    },
    "The Great Gatsby": {
        id: "The Great Gatsby",
        name: "The Great Gatsby",
        revenueCat: {
            identifier: "The Great Gatsby",
            identifierMonthly: "the_great_gatsby:monthly",
            identifierOTP: "OTP",
        },
        customStoryInput: true,
        price: 7.99,
        freeUsageSecondsAmount: 90 * 60,
        maxWordCount: 2000,
        maxSecondsPerStory: 12 * 60,
        continuationOfStory: false,
        coverImage: true,
        customCharacterLimit: 6,
        customEnvironmentLimit: 6,
        dialogues: true,
        gptModel: "gpt-3.5-turbo",
        extraStoryPrice: 0.69,
        userHistory: true,
        voicType: "Advanced",
        packageColor: "#2B593F",
        discountPercentage: 0,
    },
    "The Prime Shakespeare": {
        id: "The Prime Shakespeare",
        name: "The Prime Shakespeare",
        revenueCat: {
            identifier: "The Prime Shakespeare",
            identifierMonthly: "the_prime_shakespeare:monthly",
            identifierOTP: "OTP",
        },
        price: 29.99,
        freeUsageSecondsAmount: 300 * 60,
        maxWordCount: 3500,
        maxSecondsPerStory: 21 * 60,
        coverImage: true,
        customStoryInput: true,
        customCharacterLimit: 12,
        customEnvironmentLimit: 12,
        dialogues: true,
        extraStoryPrice: 0.99,
        gptModel: "gpt-3.5-turbo",
        userHistory: true,
        voicType: "Advanced",
        continuationOfStory: false,
        packageColor: "#492F64",
        discountPercentage: 0,
    },
    "The Greatest of All Time": {
        id: "The Greatest of All Time",
        name: "The Greatest of All Time",
        revenueCat: {
            identifier: "The Greatest of All Time",
            identifierMonthly: "the_greatest_of_all_time:monthly",
            identifierOTP: "OTP",
        },
        price: 149.99,
        freeUsageSecondsAmount: 1440 * 60,
        maxWordCount: 6000,
        maxSecondsPerStory: 30 * 60,
        gptModel: "gpt-4",
        customStoryInput: true,
        userHistory: true,
        voicType: "Advanced",
        customCharacterLimit: 30,
        customEnvironmentLimit: 30,
        dialogues: true,
        extraStoryPrice: 2.99,
        coverImage: true,
        continuationOfStory: true,
        packageColor: "#69314C",
        discountPercentage: 0,
    },
}